title: AI4EDA Conference Deadlines
description: Countdowns to top AI4EDA conference deadlines.
author: SichaoYang

domain: "sichao-yang.github.io"
baseurl: "https://sichao-yang.github.io/ai4eda-deadlines"

github_username: Sichao-Yang
github_repo: ai4eda-deadlines

markdown: kramdown

