title: xxx Conference Deadlines
description: Countdowns to top xxx conference deadlines.
author: SichaoYang

domain: "sichao-yang.github.io"
baseurl: "https://sichao-yang.github.io/ai4eda-deadlines"

github_username: Sichao-Yang
github_repo: ai4eda-deadlines


# domain: "sec-deadlines.github.io"
# baseurl: ""
# github_username: sec-deadlines
# github_repo: sec-deadlines

markdown: kramdown

